maven plugin?

diff --git a/.github/workflows/test-build-release.yml b/.github/workflows/test-build-release.yml
--- a/.github/workflows/test-build-release.yml
+++ b/.github/workflows/test-build-release.yml
@@ -89,16 +89,6 @@ jobs:
           cache: 'maven'
           cache-dependency-path: 'pom.xml'
 
-      - name: Run Test
-        continue-on-error: true
-        run: ./mvnw -Drevision=${{ github.ref_type == 'tag' && github.ref_name || steps.version.outputs.version }} --no-transfer-progress test -Pcoverage
-
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v5
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: 'target/surefire-reports/TEST-*.xml'
-
       - name: Checkov GitHub Action
         uses: bridgecrewio/checkov-action@v12
         continue-on-error: true
@@ -108,21 +98,45 @@ jobs:
           quiet: true
           soft_fail: true
 
-      - name: Sonar
-        uses: sonarsource/sonarqube-scan-action@v6
-        id: sonar
+      - name: Run Test
         continue-on-error: true
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_USER_HOME: ${{ env.SONAR_USER_HOME }}
+        run: >
+          ./mvnw
+          -Drevision=${{ github.ref_type == 'tag' && github.ref_name || steps.version.outputs.version }}
+          --no-transfer-progress
+          -Pcoverage
+          verify
+          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
+          -Dsonar.qualitygate.wait=false
+          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
+          -Dsonar.projectVersion=${{ github.ref_type == 'tag' && github.ref_name || steps.version.outputs.version }}
+          -Dsonar.links.ci=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+          -Dsonar.links.homepage=https://github.com/${{ github.repository }}
+          -Dsonar.links.issue=https://github.com/${{ github.repository }}/issues
+          -Dsonar.links.scm=${{ github.repositoryUrl }}
+          -Dsonar.sarifReportPaths=.report/checkov/results_sarif.sarif
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
         with:
-          args: >
-            -Dsonar.projectVersion=${{ github.ref_type == 'tag' && github.ref_name || steps.version.outputs.version }}
-            -Dsonar.links.ci=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-            -Dsonar.links.homepage=https://github.com/${{ github.repository }}
-            -Dsonar.links.issue=https://github.com/${{ github.repository }}/issues
-            -Dsonar.links.scm=${{ github.repositoryUrl }}
-            -Dsonar.sarifReportPaths=.report/checkov/results_sarif.sarif
+          report_paths: 'target/surefire-reports/TEST-*.xml'
+
+#      - name: Sonar
+#        uses: sonarsource/sonarqube-scan-action@v6
+#        id: sonar
+#        continue-on-error: true
+#        env:
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#          SONAR_USER_HOME: ${{ env.SONAR_USER_HOME }}
+#        with:
+#          args: >
+#            -Dsonar.projectVersion=${{ github.ref_type == 'tag' && github.ref_name || steps.version.outputs.version }}
+#            -Dsonar.links.ci=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+#            -Dsonar.links.homepage=https://github.com/${{ github.repository }}
+#            -Dsonar.links.issue=https://github.com/${{ github.repository }}/issues
+#            -Dsonar.links.scm=${{ github.repositoryUrl }}
+#            -Dsonar.sarifReportPaths=.report/checkov/results_sarif.sarif
 
       - name: Upload report
         uses: actions/upload-artifact@v4
